site_name: Telmi Wiki
site_description: Partage de connaissance de la communauté Telmi !
repo_name: heuzef/telmi-wiki
copyright: Telmi Interactive

nav:
  - ✨ Accueil: index.md
  - 🛍️ Stores:
      - Stores internationaux: stores/stores_internationaux.md
      - Stores privés: stores/stores_prives.md
      - Créer son Store Telmi: stores/creer_son_store_telmi.md
      - Héberger son Store Telmi: stores/heberger_son_store_telmi.md
  - 💳 Achats:
      - Miyoo Mini Plus: achats/miyoo_mini_plus.md
      - Carte Micro SD: achats/carte_micro_sd.md
  - 🎭 Cultures:
      - Page en construction: wip.md
  - 🪄 Créations:
      - Charte graphique Telmi: creations/charte_graphique_telmi.md
      - Musiques libres de droits: creations/musiques_libres_de_droits.md
      - Images de chapitre: creations/images_de_chapitre.md
      - Compression d'images: creations/compression_d_images.md
  - 🪛 Bricolages:
      - Détails techniques de la Miyoo Mini Plus: bricolages/details_techniques_de_la_miyoo_mini_plus.md
  - 🚀 Developments:
      - Astuces Telmi-Sync: developments/astuces_telmi_sync.md
      - Installation manuelle Telmi OS sur Linux: developments/installation_manuelle_telmi_os_sur_linux.md
      - Installation manuelle Telmi OS sur Windows: developments/installation_manuelle_telmi_os_sur_windows.md
      - Guide du developpeur Telmi OS: developments/guide_du_developpeur_telmi_os.md
      - Documentation du format des histoires: developments/documentation_du_format_des_histoires.md

theme:
  name: dracula
  logo: assets/img/telmi-wiki.png
  favicon: assets/img/favicon.ico
